### ISSUE TITLE
This repository requires a README.md

### ISSUE THREAD

**Issue by kaashmonee** [Quadmium/segtree#1]
Please include a README.md as per software engineering best practices. Thank you.

Best,
Me.

**Comment by kaashmonee** [comment]
This STILL NEEDS ADDRESSED.

**Comment by Quadmium** [comment]
Please submit a pull request for a README.md, rather than an issue, as per software engineering best practices. Thank you.

**Comment by kaashmonee** [comment]
Respectable maneuver.
